//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCD_CRUD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public int StudentAge { get; set; }
        public string StudentAddress { get; set; }
        public string StudentCity { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public short StudentStatus { get; set; }
        public byte[] StudentImage { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
